"use client";

import { useEffect, useState } from "react";
import { Icon } from "../icons";
import { formatDate, Pill, SectionHeading } from "../primitives";
import type { Snapshot } from "../types";

type AdminData={accounts:Array<{id:string;email:string;status:string;platformRole:string;personName:string;activeMemberships:number}>;workspaces:Array<{id:string;name:string;status:string;registrationMode:string;activeSeats:number}>;pendingInvitations:number;openCases:number;recentActivity:Array<{action:string;resourceType:string;resourceId:string;occurredAt:string}>;health:{status:string;schemaVersion:number;corpusRevision:number}};

export function AdminConsole({data,onViewAs}:{data:Snapshot;onViewAs:(accountId:string)=>Promise<void>}) {
  const [admin,setAdmin]=useState<AdminData|null>(null); const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/admin",{headers:{"x-interlocks-account":data.realActor.accountId}}).then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load administration");setAdmin(body);}).catch((caught)=>setError(caught.message));},[data.realActor.accountId]);
  if(error)return <article className="card panel"><p className="form-error">{error}</p></article>;
  if(!admin)return <article className="card panel"><p>Loading the audited administrative view…</p></article>;
  return <div className="page-stack"><section className="stat-grid"><article className="stat card"><span className="stat-icon blue"><Icon name="building"/></span><div><p>Workspaces</p><strong>{admin.workspaces.length}</strong><span>Across the platform</span></div></article><article className="stat card"><span className="stat-icon green"><Icon name="people"/></span><div><p>Active seats</p><strong>{admin.workspaces.reduce((sum,item)=>sum+item.activeSeats,0)}</strong><span>Current memberships</span></div></article><article className="stat card"><span className="stat-icon yellow"><Icon name="review"/></span><div><p>Open cases</p><strong>{admin.openCases}</strong><span>All workspaces</span></div></article><article className="stat card"><span className="stat-icon red"><Icon name="shield"/></span><div><p>Schema</p><strong>v{admin.health.schemaVersion}</strong><span>Corpus {admin.health.corpusRevision}</span></div></article></section><div className="portfolio-grid"><article className="card panel"><SectionHeading eyebrow="Global administration" title="Workspaces"/><div className="dense-list">{admin.workspaces.map((item)=><div key={item.id}><Pill tone={item.status==="ACTIVE"?"green":"neutral"}>{item.status}</Pill><strong>{item.name}</strong><p>{item.activeSeats} active seats</p><span>{item.registrationMode} registration</span></div>)}</div></article><article className="card panel"><SectionHeading eyebrow="Identity boundary" title="Accounts"/><div className="admin-accounts">{admin.accounts.map((item)=><div className="admin-account" key={item.id}><div><Pill tone={item.platformRole==="SUPERADMIN"?"red":"blue"}>{item.platformRole}</Pill><strong>{item.personName}</strong><p>{item.email} · {item.activeMemberships} active memberships</p></div>{item.id!==data.realActor.accountId?<button className="secondary-button" onClick={()=>void onViewAs(item.id)}><Icon name="people"/>View as</button>:null}</div>)}</div></article></div><article className="card panel"><SectionHeading eyebrow="Platform activity" title="Recent global events"/><div className="timeline">{admin.recentActivity.map((item)=><div key={`${item.occurredAt}-${item.resourceId}`}><span/><div><strong>{item.action.replaceAll("."," ")}</strong><p>{item.resourceType} · {item.resourceId}</p></div><time>{formatDate(item.occurredAt,true)}</time></div>)}</div></article><article className="boundary-note"><Icon name="shield"/><div><strong>View-as is explicit, read-only, reasoned, and audited.</strong><p>It changes the visible person and tenant boundary without changing the real acting account.</p></div></article></div>;
}
