"use client";

import { FormEvent, useMemo, useState } from "react";
import { Icon } from "../icons";
import { Empty, formatDate, Pill, SectionHeading, SubmitButton, titleCase } from "../primitives";
import type { Command, Snapshot } from "../types";

export function DataPage({data,command}:{data:Snapshot;command:Command}) {
  const [type,setType]=useState("ENTITIES"); const [csv,setCsv]=useState("name,kind,jurisdiction\nExample Organization,ORGANIZATION,DC"); const [preview,setPreview]=useState<{rows:Array<Record<string,string>>;errors:Array<{row:number;column?:string;message:string}>;valid:boolean}|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");command("import.preview",{type,csv}).then((result)=>setPreview(result as typeof preview)).catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to preview")).finally(()=>setBusy(false));};
  const commit=()=>{setBusy(true);command("import.commit",{type,csv,filename:`${type.toLowerCase()}.csv`}).then(()=>setPreview(null)).catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to import")).finally(()=>setBusy(false));};
  return <div className="data-layout"><article className="card panel"><SectionHeading eyebrow="Transactional ingestion" title="CSV import"/><p className="page-intro">Preview validates the entire batch. Commit is all-or-nothing and advances the recorded knowledge-corpus revision.</p><form className="stacked-form" onSubmit={submit}><label><span>Resource type</span><select value={type} onChange={(event)=>{setType(event.target.value);setPreview(null);}}><option>ENTITIES</option><option>ALIASES</option><option>MATTERS</option><option>PARTIES</option><option>RELATIONSHIPS</option><option>LEDGER_ENTRIES</option></select></label><label><span>CSV</span><textarea value={csv} onChange={(event)=>setCsv(event.target.value)} rows={12} className="code-input" spellCheck={false}/></label>{error?<p className="form-error" role="alert">{error}</p>:null}<SubmitButton busy={busy} label="Validate preview"/></form>{preview?<div className="import-preview"><header><Pill tone={preview.valid?"green":"red"}>{preview.valid?"VALID":"HAS ERRORS"}</Pill><strong>{preview.rows.length} rows</strong></header>{preview.errors.map((item)=><p key={`${item.row}-${item.column}-${item.message}`}>Row {item.row}{item.column?`, ${item.column}`:""}: {item.message}</p>)}{preview.valid?<button className="primary-button" disabled={busy} onClick={commit}><Icon name="upload"/>Commit all rows</button>:null}</div>:null}</article><aside className="page-stack"><article className="card panel"><SectionHeading eyebrow="Complete tenant package" title="Exports"/><a className="export-card" href={`/api/export?workspace=${data.workspace?.id||""}&kind=workspace`}><span><Icon name="building"/></span><div><strong>Workspace export</strong><p>Knowledge, checks, cases, evidence, controls, people, and audit history.</p></div><Icon name="download"/></a><a className="export-card" href="/api/export?kind=personal"><span><Icon name="ledger"/></span><div><strong>Personal ledger export</strong><p>Only this person&apos;s portable and restricted entries.</p></div><Icon name="download"/></a>{data.checks[0]?<a className="export-card" href={`/api/export?workspace=${data.workspace?.id||""}&kind=check&resourceId=${data.checks[0].id}`}><span><Icon name="search"/></span><div><strong>Latest check package</strong><p>Subjects, hits, evidence, cases, determinations, consent, and screens.</p></div><Icon name="download"/></a>:null}</article><article className="card panel"><SectionHeading eyebrow="Replaceable boundaries" title="Runtime"/><dl className="settings-facts"><div><dt>Database</dt><dd>{data.configuration.databaseDriver}</dd></div><div><dt>Object store</dt><dd>{data.configuration.objectStoreDriver}</dd></div><div><dt>Schema migrations</dt><dd>{data.migrations.length}</dd></div><div><dt>Corpus revision</dt><dd>{data.corpusRevision}</dd></div></dl></article></aside></div>;
}

export function AuditPage({data}:{data:Snapshot}) {
  const [query,setQuery]=useState(""); const events=useMemo(()=>data.audit.filter((event)=>!query||[event.action,event.actorName,event.resourceType,event.resourceId,event.authorityUsed].some((value)=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[data.audit,query]);
  return <article className="card panel page-panel"><div className="toolbar"><SectionHeading eyebrow="Append-only evidence" title="Audit trail"/><label className="inline-search"><Icon name="search"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search action, actor, or resource" aria-label="Search audit trail"/></label></div><div className="audit-table"><div className="audit-head"><span>Time</span><span>Actor / authority</span><span>Action</span><span>Resource</span><span>Reason</span></div>{events.map((event)=><div className="audit-row" key={event.id}><time>{formatDate(event.occurredAt,true)}</time><span><strong>{event.actorName||"System"}</strong><small>{event.authorityUsed}</small></span><span>{event.action.replaceAll("."," ")}</span><span><Pill>{titleCase(event.resourceType)}</Pill><code>{event.resourceId.slice(0,14)}</code></span><span>{event.reason||"—"}</span></div>)}</div>{!events.length?<Empty title="No matching events" message="Try a broader audit query."/>:null}</article>;
}
