"use client";

import { FormEvent, useEffect, useState } from "react";
import { Icon } from "../icons";
import { Empty, formatDate, Modal, Pill, SectionHeading, SubmitButton, titleCase } from "../primitives";
import type { Command, Snapshot } from "../types";

export function PortfolioPage({data,command}:{data:Snapshot;command:Command}) {
  const [create,setCreate]=useState<"entity"|"matter"|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const input:Record<string,unknown>=Object.fromEntries(new FormData(event.currentTarget));if(create==="entity"){input.aliases=String(input.aliasesText||"").split(",").map((item)=>item.trim()).filter(Boolean);delete input.aliasesText;}setBusy(true);setError("");command(`${create}.create`,input).then(()=>setCreate(null)).catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to save")).finally(()=>setBusy(false));};
  return <><div className="portfolio-grid"><article className="card panel"><SectionHeading eyebrow="Canonical knowledge" title="Entities" action={<button className="secondary-button" onClick={()=>setCreate("entity")}><Icon name="plus"/>Entity</button>}/><div className="dense-list">{data.entities.map((item)=><div key={item.id}><span className="record-icon"><Icon name={item.kind==="PERSON"?"people":"building"}/></span><strong>{item.canonicalName}</strong><p>{titleCase(item.kind)}{item.jurisdiction?` · ${item.jurisdiction}`:""}</p>{item.aliases.length?<span>Also known as {item.aliases.join(", ")}</span>:null}</div>)}</div></article><article className="card panel"><SectionHeading eyebrow="Institutional work" title="Matters" action={<button className="primary-button" onClick={()=>setCreate("matter")}><Icon name="plus"/>Matter</button>}/><div className="dense-list">{data.matters.map((item)=><div key={item.id}><Pill tone={item.status==="ACTIVE"?"green":"neutral"}>{item.status}</Pill><strong>{item.code} — {item.title}</strong><p>{titleCase(item.matterType)} · {titleCase(item.representationStatus)}</p><span>{item.partyCount} parties · {item.ownerName||"No owner"} · opened {formatDate(item.openedAt)}</span></div>)}</div></article></div>{create?<Modal title={create==="entity"?"Create canonical entity":"Open a matter"} eyebrow="Portfolio" onClose={()=>setCreate(null)}><form className="modal-form" onSubmit={submit}>{create==="entity"?<><label><span>Canonical name</span><input name="canonicalName" required/></label><div className="form-grid"><label><span>Kind</span><select name="kind"><option>ORGANIZATION</option><option>PERSON</option><option>PROPERTY</option><option>GOVERNMENT</option><option>OTHER</option></select></label><label><span>Jurisdiction</span><input name="jurisdiction"/></label></div><label><span>Aliases <small>comma-separated</small></span><input name="aliasesText"/></label></>:<><div className="form-grid"><label><span>Code</span><input name="code" required/></label><label><span>Type</span><select name="matterType"><option>REPRESENTATION</option><option>PROCUREMENT</option><option>HIRING</option><option>INVESTIGATION</option><option>ADVISORY</option></select></label></div><label><span>Title</span><input name="title" required/></label><div className="form-grid"><label><span>Representation status</span><select name="representationStatus"><option>PROPOSED</option><option>CURRENT</option><option>FORMER</option></select></label><label><span>Sensitivity</span><select name="sensitivity"><option>STANDARD</option><option>ELEVATED</option><option>RESTRICTED</option></select></label></div><input type="hidden" name="ownerPersonId" value={data.actor.personId}/></>}{error?<p className="form-error">{error}</p>:null}<footer><button type="button" className="secondary-button" onClick={()=>setCreate(null)}>Cancel</button><SubmitButton busy={busy} label="Create"/></footer></form></Modal>:null}</>;
}

export function SettingsPage({data,command}:{data:Snapshot;command:Command}) {
  const [invite,setInvite]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const roles=data.actor.memberships.find((item)=>item.workspaceId===data.workspace?.id)?.roles||[]; const admin=roles.includes("FIRMADMIN")||data.actor.platformRole==="SUPERADMIN";
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget));const values:Record<string,unknown>={...raw,roles:[String(raw.role)]};delete values.role;setBusy(true);setError("");command("invitation.create",values).then((result)=>{const token=(result as {token:string}).token;setError(`Invitation created — copy ${window.location.origin}/invite/${token}`);}).catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to save")).finally(()=>setBusy(false));};
  return <><div className="settings-layout"><article className="card panel"><SectionHeading eyebrow="Firm administration" title="People and roles" action={admin?<button className="primary-button" onClick={()=>setInvite(true)}><Icon name="plus"/>Invite</button>:undefined}/><div className="member-table"><div className="member-head"><span>Person</span><span>Roles</span><span>Status</span><span>Seat</span></div>{data.memberships.map((item)=><div className="member-row" key={item.id}><div><span className="avatar">{item.personName.split(" ").map((part)=>part[0]).slice(0,2).join("")}</span><span><strong>{item.personName}</strong><small>{item.email||"No account attached"}</small></span></div><span>{item.roles.map((role)=><Pill key={role} tone="blue">{role}</Pill>)}</span><Pill tone={item.status==="ACTIVE"?"green":"neutral"}>{item.status}</Pill><span>{item.status==="ACTIVE"?"Billable":"No"}</span></div>)}</div></article><aside className="page-stack"><article className="card panel"><SectionHeading eyebrow="Workspace policy" title={data.workspace?.name||"No workspace"}/><dl className="settings-facts"><div><dt>Registration</dt><dd>{data.workspace?.registrationMode}</dd></div><div><dt>Current billable seats</dt><dd>{data.stats.currentBillableSeats}</dd></div><div><dt>Environment</dt><dd>{data.configuration.environment}</dd></div><div><dt>Auth provider</dt><dd>{data.configuration.authProvider}</dd></div></dl></article><article className="card panel"><SectionHeading eyebrow="Open invitations" title="Pending access"/>{data.invitations.map((item)=><div className="invite-row" key={item.id}><div><strong>{item.email}</strong><span>{item.roles.join(", ")} · expires {formatDate(item.expiresAt)}</span></div><Pill tone="yellow">{item.status}</Pill></div>)}{!data.invitations.length?<Empty title="No invitations" message="There are no invitations in this workspace."/>:null}</article>{data.configuration.demoMode?<article className="card panel danger-zone"><SectionHeading eyebrow="Development only" title="Canonical demo workspace"/><p>Reset all demonstration records to the tested fixture. This operation is unavailable in production.</p><button className="danger-button" onClick={()=>void command("demo.reset")}>Reset demo data</button></article>:null}</aside></div>{invite?<Modal title="Invite a workspace member" eyebrow="Firm administration" onClose={()=>setInvite(false)}><form className="modal-form" onSubmit={submit}><label><span>Email</span><input type="email" name="email" required/></label><label><span>Role</span><select name="role"><option>MEMBER</option><option>REVIEWER</option><option>FIRMADMIN</option></select></label>{error?<p className="form-error">{error}</p>:null}<footer><button className="secondary-button" type="button" onClick={()=>setInvite(false)}>Cancel</button><SubmitButton busy={busy} label="Create invitation"/></footer></form></Modal>:null}</>;
}

type AdminData={accounts:Array<{id:string;email:string;status:string;platformRole:string;personName:string;activeMemberships:number}>;workspaces:Array<{id:string;name:string;status:string;registrationMode:string;activeSeats:number}>;pendingInvitations:number;openCases:number;recentActivity:Array<{action:string;resourceType:string;resourceId:string;occurredAt:string}>;health:{status:string;schemaVersion:number;corpusRevision:number}};
export function AdminPage({data}:{data:Snapshot}) {
  const [admin,setAdmin]=useState<AdminData|null>(null); const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/admin",{headers:{"x-interlocks-account":data.realActor.accountId}}).then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load administration");setAdmin(body);}).catch((caught)=>setError(caught.message));},[data.realActor.accountId]);
  if(error)return <article className="card panel"><p className="form-error">{error}</p></article>; if(!admin)return <article className="card panel"><p>Loading the audited administrative view…</p></article>;
  return <div className="page-stack"><section className="stat-grid"><article className="stat card"><span className="stat-icon blue"><Icon name="building"/></span><div><p>Workspaces</p><strong>{admin.workspaces.length}</strong><span>Across the platform</span></div></article><article className="stat card"><span className="stat-icon green"><Icon name="people"/></span><div><p>Active seats</p><strong>{admin.workspaces.reduce((sum,item)=>sum+item.activeSeats,0)}</strong><span>Current membership events</span></div></article><article className="stat card"><span className="stat-icon yellow"><Icon name="review"/></span><div><p>Open cases</p><strong>{admin.openCases}</strong><span>All workspaces</span></div></article><article className="stat card"><span className="stat-icon red"><Icon name="shield"/></span><div><p>Schema</p><strong>v{admin.health.schemaVersion}</strong><span>Corpus {admin.health.corpusRevision}</span></div></article></section><div className="portfolio-grid"><article className="card panel"><SectionHeading eyebrow="Global administration" title="Workspaces"/><div className="dense-list">{admin.workspaces.map((item)=><div key={item.id}><Pill tone={item.status==="ACTIVE"?"green":"neutral"}>{item.status}</Pill><strong>{item.name}</strong><p>{item.activeSeats} active seats</p><span>{item.registrationMode} registration</span></div>)}</div></article><article className="card panel"><SectionHeading eyebrow="Identity boundary" title="Accounts"/><div className="dense-list">{admin.accounts.map((item)=><div key={item.id}><Pill tone={item.platformRole==="SUPERADMIN"?"red":"blue"}>{item.platformRole}</Pill><strong>{item.personName}</strong><p>{item.email}</p><span>{item.activeMemberships} active memberships</span></div>)}</div></article></div><article className="boundary-note"><Icon name="shield"/><div><strong>SUPERADMIN access is explicit and audited.</strong><p>Global administration is not an implicit firm role. Cross-tenant support must use a reasoned, read-only view-as session.</p></div></article></div>;
}
