"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Icon } from "../icons";
import { containDialogFocus, Empty, formatDate, Modal, Pill, SectionHeading, SubmitButton, TrafficLight } from "../primitives";
import type { CaseItem, Command, Snapshot } from "../types";

function CaseRows({items,onOpen}:{items:CaseItem[];onOpen:(item:CaseItem)=>void}) {
  if (!items.length) return <Empty title="No review cases" message="Nothing in this view currently requires attention."/>;
  return <div className="record-list">{items.map((item)=><button className="record case-record" key={item.id} onClick={()=>onOpen(item)}><TrafficLight state={item.workflowState} compact/><div className="record-main"><div><strong>{item.title}</strong><Pill>{item.reference}</Pill></div><p>{item.summary}</p><footer><span>{item.personName || "Unassigned person"}</span><span>{item.matterCode || "No matter"}</span><span>{item.assigneeName || "Unassigned"}</span></footer></div><div className="record-end"><Pill tone="blue">{item.humanDisposition.replaceAll("_"," ")}</Pill><time>{formatDate(item.updatedAt)}</time><Icon name="arrow"/></div></button>)}</div>;
}

export function DashboardPage({data,onOpenCase,onNavigate,onCommand}:{data:Snapshot;onOpenCase:(item:CaseItem)=>void;onNavigate:(view:"checks"|"review")=>void;onCommand:Command}) {
  const urgent = data.cases.filter((item)=>item.workflowState!=="GREEN").slice(0,4);
  const controls = data.controls.filter((item)=>item.status==="OPEN").slice(0,4);
  return <div className="page-stack">
    <section className="stat-grid">
      <article className="stat card"><span className="stat-icon red"><Icon name="alert"/></span><div><p>Holds</p><strong>{data.stats.red}</strong><span>Do not proceed</span></div></article>
      <article className="stat card"><span className="stat-icon yellow"><Icon name="review"/></span><div><p>Needs review</p><strong>{data.stats.yellow}</strong><span>Human attention</span></div></article>
      <article className="stat card"><span className="stat-icon green"><Icon name="check"/></span><div><p>Clear to proceed</p><strong>{data.stats.green}</strong><span>No unresolved issue</span></div></article>
      <article className="stat card"><span className="stat-icon blue"><Icon name="people"/></span><div><p>Active seats</p><strong>{data.stats.currentBillableSeats}</strong><span>{data.workspace?.name}</span></div></article>
    </section>
    <div className="dashboard-grid">
      <article className="card panel span-two"><SectionHeading eyebrow="Action queue" title="What needs attention" action={<button className="text-button" onClick={()=>onNavigate("review")}>Open review queue <Icon name="arrow" size={14}/></button>}/><CaseRows items={urgent} onOpen={onOpenCase}/></article>
      <article className="card panel"><SectionHeading eyebrow="Current knowledge" title="Corpus revision"/><div className="revision-mark"><strong>{data.corpusRevision}</strong><span>Every check records the exact revision it used.</span></div><div className="mini-metrics"><div><b>{data.checks.length}</b><span>Checks run</span></div><div><b>{data.checks.filter((item)=>item.reReviewSuggested).length}</b><span>Re-review suggested</span></div></div><button className="secondary-button full" onClick={()=>onNavigate("checks")}><Icon name="search"/>Run a conflict check</button></article>
      <article className="card panel span-two"><SectionHeading eyebrow="Implementation" title="Open controls"/><div className="control-list">{controls.map((item)=><div className="control-row" key={item.id}><button aria-label={`Complete ${item.description}`} onClick={()=>onCommand("control.complete",{},item.id)}><Icon name="check" size={14}/></button><div><strong>{item.description}</strong><span>{item.ownerName} · {item.caseReference}</span></div>{item.mandatory?<Pill tone="red">Mandatory</Pill>:<Pill>Advisory</Pill>}</div>)}</div>{!controls.length?<Empty title="No open controls" message="Every assigned control is complete."/>:null}</article>
      <article className="card panel"><SectionHeading eyebrow="Recent activity" title="Attributable history"/><div className="timeline">{data.audit.slice(0,5).map((event)=><div key={event.id}><span/><div><strong>{event.action.replaceAll("."," ")}</strong><p>{event.actorName || "System"} · {event.authorityUsed}</p></div><time>{formatDate(event.occurredAt)}</time></div>)}</div></article>
    </div>
  </div>;
}

export function ReviewPage({data,command}:{data:Snapshot;command:Command}) {
  const [state,setState]=useState("OPEN"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<CaseItem|null>(null);
  const cases=useMemo(()=>data.cases.filter((item)=>{
    const stateMatch=state==="OPEN"?!["CLOSED","DECLINED","WITHDRAWN"].includes(item.status):state==="ALL"||item.workflowState===state;
    return stateMatch&&(!query||[item.title,item.reference,item.personName,item.entityName,item.matterCode].some((value)=>String(value||"").toLowerCase().includes(query.toLowerCase())));
  }),[data.cases,state,query]);
  return <><article className="card panel page-panel"><div className="toolbar"><div className="segmented">{["OPEN","RED","YELLOW","GREEN","ALL"].map((value)=><button className={state===value?"active":""} onClick={()=>setState(value)} key={value}>{value}</button>)}</div><label className="inline-search"><Icon name="search"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search cases" aria-label="Search cases"/></label></div><CaseRows items={cases} onOpen={setSelected}/></article>{selected?<CaseDrawer item={data.cases.find((item)=>item.id===selected.id)||selected} data={data} command={command} onClose={()=>setSelected(null)}/>:null}</>;
}

function CaseDrawer({item,data,command,onClose}:{item:CaseItem;data:Snapshot;command:Command;onClose:()=>void}) {
  const [tab,setTab]=useState<"review"|"consent"|"screen">("review"); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const drawer=useRef<HTMLElement>(null);
  useEffect(()=>{const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;drawer.current?.focus();return()=>previous?.focus();},[]);
  const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await work();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to save");}finally{setBusy(false);}};
  const submitDetermination=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));void run(()=>command("case.action",{type:"determination",...values},item.id));};
  const submitNote=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const body=String(new FormData(form).get("body")||"");void run(async()=>{await command("case.action",{type:"note",body},item.id);form.reset();});};
  const submitConsent=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();void run(()=>command("consent.create",Object.fromEntries(new FormData(event.currentTarget)),item.id));};
  const submitScreen=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();void run(()=>command("screen.create",Object.fromEntries(new FormData(event.currentTarget)),item.id));};
  const notes=data.notes.filter((note)=>note.caseId===item.id); const determinations=data.determinations.filter((entry)=>entry.caseId===item.id); const controls=data.controls.filter((entry)=>entry.caseId===item.id); const consents=data.consents.filter((entry)=>entry.caseId===item.id); const screens=data.screens.filter((entry)=>entry.caseId===item.id);
  return <div className="drawer-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><aside ref={drawer} tabIndex={-1} onKeyDown={(event)=>containDialogFocus(event,drawer.current,onClose)} className="drawer" role="dialog" aria-modal="true" aria-labelledby="case-title"><header><div><p>{item.reference}</p><h2 id="case-title">{item.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close case"><Icon name="close"/></button></header><div className="drawer-scroll"><div className="case-banner"><TrafficLight state={item.workflowState}/><Pill tone="blue">{item.humanDisposition.replaceAll("_"," ")}</Pill><Pill>{item.status.replaceAll("_"," ")}</Pill></div><p className="case-summary">{item.summary}</p><dl className="facts"><div><dt>Person</dt><dd>{item.personName||"—"}</dd></div><div><dt>Entity</dt><dd>{item.entityName||"—"}</dd></div><div><dt>Matter</dt><dd>{item.matterCode||"—"}<small>{item.matterTitle}</small></dd></div><div><dt>Reviewer</dt><dd>{item.assigneeName||"—"}<small>Due {formatDate(item.reviewDueAt)}</small></dd></div></dl><div className="drawer-tabs">{(["review","consent","screen"] as const).map((value)=><button className={tab===value?"active":""} key={value} onClick={()=>setTab(value)}>{value}</button>)}</div>
    {tab==="review"?<><section className="drawer-section"><h3>Human determinations</h3>{determinations.map((entry)=><div className="history-card" key={entry.id}><Pill tone="blue">{entry.disposition.replaceAll("_"," ")}</Pill><p>{entry.rationale}</p><span>{entry.determinedBy} · {entry.ruleBasis||"No rule basis recorded"} · {formatDate(entry.determinedAt,true)}</span></div>)}{!determinations.length?<p className="muted">No professional determination has been recorded.</p>:null}</section><section className="drawer-section"><h3>Review notes</h3>{notes.map((note)=><div className="note" key={note.id}><strong>{note.author}<time>{formatDate(note.createdAt,true)}</time></strong><p>{note.body}</p></div>)}<form className="stacked-form" onSubmit={submitNote}><textarea name="body" required rows={3} placeholder="Evidence, question, or outside information needed…"/><button className="secondary-button" disabled={busy}>Add review note</button></form></section><section className="drawer-section"><h3>Record human disposition</h3><form className="stacked-form" onSubmit={submitDetermination}><label><span>Disposition</span><select name="disposition" required defaultValue="UNREVIEWED"><option>UNREVIEWED</option><option>NO_CONFLICT</option><option>CONFLICT_CONSENTABLE</option><option>CONFLICT_NONCONSENTABLE</option><option>CONSENT_REQUIRED</option><option>SCREEN_REQUIRED</option><option>CLEARED</option><option>DECLINE</option><option>WITHDRAW</option><option>OTHER</option></select></label><label><span>Rationale</span><textarea name="rationale" required rows={4} placeholder="Record the facts considered and the professional judgment applied."/></label><div className="form-grid"><label><span>Rule or policy basis</span><input name="ruleBasis" placeholder="e.g. D.C. Rule 1.7"/></label><label><span>Jurisdiction</span><input name="jurisdiction" placeholder="District of Columbia"/></label></div><label><span>Management control <small>optional</small></span><input name="controlDescription" placeholder="Create an owned, mandatory action"/></label><div className="form-grid"><label><span>Owner</span><select name="ownerPersonId" defaultValue={data.actor.personId}>{data.memberships.filter((m)=>m.status==="ACTIVE").map((m)=><option value={m.personId} key={m.id}>{m.personName}</option>)}</select></label><label><span>Due</span><input name="dueAt" type="date"/></label></div><SubmitButton busy={busy} label="Record determination"/></form></section></>:null}
    {tab==="consent"?<><section className="drawer-section"><h3>Consent and waivers</h3>{consents.map((entry)=><div className="history-card" key={entry.id}><Pill tone={entry.status==="OBTAINED"?"green":"yellow"}>{entry.status}</Pill><p>{entry.scope}</p><span>{entry.evidenceRequirement||"Human-defined evidence requirement"} · {entry.affectedEntityName||"Affected entity pending"}</span></div>)}<form className="stacked-form" onSubmit={submitConsent}><label><span>Affected entity</span><select name="affectedEntityId" defaultValue={item.entityId||""}><option value="">Select entity</option>{data.entities.map((entity)=><option value={entity.id} key={entity.id}>{entity.canonicalName}</option>)}</select></label><div className="form-grid"><label><span>Status</span><select name="status" defaultValue="REQUESTED"><option>REQUESTED</option><option>OBTAINED</option><option>DECLINED</option><option>REVOKED</option><option>EXPIRED</option><option>SUPERSEDED</option></select></label><label><span>Evidence requirement</span><select name="evidenceRequirement" defaultValue="CONFIRMED_IN_WRITING"><option>CONFIRMED_IN_WRITING</option><option>SIGNED_WRITING</option><option>OTHER_REQUIREMENT</option></select></label></div><label><span>Scope</span><textarea name="scope" required rows={3}/></label><div className="form-grid"><label><span>Rule basis</span><input name="ruleBasis"/></label><label><span>Jurisdiction</span><input name="jurisdiction"/></label></div><SubmitButton busy={busy} label="Record consent"/></form><p className="model-note"><Icon name="shield"/>Recording consent never clears the case automatically.</p></section></>:null}
    {tab==="screen"?<><section className="drawer-section"><h3>Professional screens</h3>{screens.map((entry)=><div className="history-card" key={entry.id}><Pill tone={entry.status==="ACTIVE"?"green":"yellow"}>{entry.status}</Pill><p>{entry.restrictions}</p><span>{entry.screenedPersonName} · effective {formatDate(entry.effectiveAt,true)}</span></div>)}<form className="stacked-form" onSubmit={submitScreen}><label><span>Screened person</span><select name="screenedPersonId" required defaultValue={item.personId||""}>{data.memberships.map((m)=><option value={m.personId} key={m.id}>{m.personName}</option>)}</select></label><div className="form-grid"><label><span>Effective at</span><input type="datetime-local" name="effectiveAt" required/></label><label><span>Status</span><select name="status" defaultValue="PROPOSED"><option>PROPOSED</option><option>ACTIVE</option><option>INCOMPLETE</option><option>ENDED</option><option>BREACHED</option></select></label></div><label><span>Participation and access restrictions</span><textarea name="restrictions" required rows={3}/></label><label><span>Fee restrictions</span><input name="feeRestrictions"/></label><label><span>Communication restrictions</span><input name="communicationsRestrictions"/></label><label><span>Notice requirements and recipients</span><input name="noticeRequirements"/><input name="noticeRecipients" placeholder="Recipients"/></label><SubmitButton busy={busy} label="Create screen"/></form><p className="model-note"><Icon name="shield"/>A screen is operational evidence, not a machine cure.</p></section></>:null}
    {controls.length?<section className="drawer-section"><h3>Controls</h3>{controls.map((control)=><div className="control-row" key={control.id}><button disabled={control.status==="COMPLETE"} onClick={()=>void run(()=>command("control.complete",{},control.id))}><Icon name="check" size={14}/></button><div><strong>{control.description}</strong><span>{control.ownerName} · {control.status}</span></div></div>)}</section>:null}{error?<p className="form-error">{error}</p>:null}</div></aside></div>;
}

export function DisclosureDialog({data,command,onClose}:{data:Snapshot;command:Command;onClose:()=>void}) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const input=Object.fromEntries(new FormData(event.currentTarget));command("disclosure.create",input).then(onClose).catch((caught)=>setError(caught instanceof Error?caught.message:"Unable to save")).finally(()=>setBusy(false));};
  return <Modal title="Record a relationship" eyebrow="New disclosure" onClose={onClose}><form className="modal-form" onSubmit={submit}><div className="form-grid"><label><span>Covered person</span><select name="personId" required>{data.memberships.filter((m)=>m.status==="ACTIVE").map((m)=><option value={m.personId} key={m.id}>{m.personName}</option>)}</select></label><label><span>Matter</span><select name="matterId" required>{data.matters.map((m)=><option value={m.id} key={m.id}>{m.code} — {m.title}</option>)}</select></label></div><div className="form-grid"><label><span>Entity</span><select name="entityId" required>{data.entities.map((entity)=><option value={entity.id} key={entity.id}>{entity.canonicalName}</option>)}</select></label><label><span>Relationship type</span><input name="relationshipType" required placeholder="e.g. Former client"/></label></div><label><span>What is the connection?</span><textarea name="description" required rows={4}/></label><div className="form-grid"><label><span>Disclosure class</span><select name="disclosureClass" defaultValue="FIRM_ONLY"><option>PORTABLE</option><option>RESTRICTED</option><option>CONSENT_REQUIRED</option><option>FIRM_ONLY</option></select></label><label><span>Effective from</span><input name="startDate" type="date"/></label></div>{error?<p className="form-error">{error}</p>:null}<footer><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><SubmitButton busy={busy} label="Record and queue"/></footer></form></Modal>;
}
